import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navbar from '../components/Navbar';
import QueryProvider from '../components/provider/query-provider';
import { ThemeProvider } from '../components/provider/theme-provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <QueryProvider>
          <ThemeProvider>
            <main className='mx-auto min-h-screen max-w-6xl space-y-10 py-10'>
              <Navbar />
              {children}
            </main>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
